package com.example.BACKEND_OLDTECH_WEBSITE.ETL.Model;

import com.example.BACKEND_OLDTECH_WEBSITE.Model.User;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.Duration;

/**
 * Admin Alert Model - Simple Version
 * Quản lý cảnh báo hệ thống đơn giản
 */
@Entity
@Table(name = "admin_alert")
@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class AdminAlert {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "alert_id")
    private Long alertId;

    // ===============================
    // BASIC FIELDS
    // ===============================
    
    @Column(name = "alert_code", length = 50, nullable = false, unique = true)
    private String alertCode;

    @Enumerated(EnumType.STRING)
    @Column(name = "alert_category", nullable = false)
    private AlertCategory alertCategory;

    @Column(name = "alert_type", length = 100, nullable = false)
    private String alertType;

    @Column(name = "alert_title", nullable = false)
    private String alertTitle;

    @Column(name = "alert_description", columnDefinition = "TEXT")
    private String alertDescription;

    // ===============================
    // STATUS
    // ===============================
    
    @Enumerated(EnumType.STRING)
    @Column(name = "severity_level", nullable = false)
    private SeverityLevel severityLevel = SeverityLevel.MEDIUM;

    @Enumerated(EnumType.STRING)
    @Column(name = "priority_level", nullable = false)
    private PriorityLevel priorityLevel = PriorityLevel.NORMAL;

    @Enumerated(EnumType.STRING)
    @Column(name = "alert_status", nullable = false)
    private AlertStatus alertStatus = AlertStatus.ACTIVE;

    @Column(name = "is_auto_generated", nullable = false)
    private Boolean isAutoGenerated = true;

    // ===============================
    // METRICS (OPTIONAL)
    // ===============================
    
    @Column(name = "metric_name", length = 100)
    private String metricName;

    @Column(name = "current_value", precision = 20, scale = 4)
    private BigDecimal currentValue;

    @Column(name = "threshold_value", precision = 20, scale = 4)
    private BigDecimal thresholdValue;

    @Enumerated(EnumType.STRING)
    @Column(name = "threshold_type")
    private ThresholdType thresholdType;

    // ===============================
    // BASIC CONTEXT
    // ===============================
    
    @Column(name = "affected_component", length = 100)
    private String affectedComponent;

    @Enumerated(EnumType.STRING)
    @Column(name = "impact_level")
    private ImpactLevel impactLevel;

    @Column(name = "business_impact", columnDefinition = "TEXT")
    private String businessImpact;

    // ===============================
    // RELATED DATA
    // ===============================
    
    @Column(name = "related_entity_type", length = 50)
    private String relatedEntityType;

    @Column(name = "related_entity_id", columnDefinition = "BIGINT UNSIGNED")
    private Long relatedEntityId;

    // ===============================
    // ACTIONS
    // ===============================
    
    @Column(name = "suggested_action", columnDefinition = "TEXT")
    private String suggestedAction;

    @Column(name = "manual_action_required", nullable = false)
    private Boolean manualActionRequired = false;

    // ===============================
    // TRACKING
    // ===============================
    
    @Column(name = "is_read", nullable = false)
    private Boolean isRead = false;

    @Column(name = "is_resolved", nullable = false)
    private Boolean isResolved = false;

    // ===============================
    // ACKNOWLEDGMENT & RESOLUTION
    // ===============================
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "acknowledged_by", referencedColumnName = "user_id")
    private User acknowledgedBy;

    @Column(name = "acknowledged_at")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime acknowledgedAt;

    @Column(name = "acknowledged_note", columnDefinition = "TEXT")
    private String acknowledgedNote;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "resolved_by", referencedColumnName = "user_id")
    private User resolvedBy;

    @Column(name = "resolved_at")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime resolvedAt;

    @Column(name = "resolution_note", columnDefinition = "TEXT")
    private String resolutionNote;

    @Column(name = "resolution_time_minutes", columnDefinition = "INT UNSIGNED")
    private Integer resolutionTimeMinutes;

    // ===============================
    // NOTIFICATION
    // ===============================
    
    @Column(name = "notification_sent", nullable = false)
    private Boolean notificationSent = false;

    // ===============================
    // RECURRENCE
    // ===============================
    
    @Column(name = "is_recurring", nullable = false)
    private Boolean isRecurring = false;

    @Column(name = "occurrence_count", columnDefinition = "INT UNSIGNED DEFAULT 1", nullable = false)
    private Integer occurrenceCount = 1;

    // ===============================
    // METADATA
    // ===============================
    
    @Column(name = "source_system", length = 100)
    private String sourceSystem;

    @Column(name = "alert_version", length = 10)
    private String alertVersion = "1.0";

    // ===============================
    // TIMESTAMPS
    // ===============================
    
    @Column(name = "created_at", nullable = false, updatable = false)
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime updatedAt;    @Column(name = "expires_at")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime expiresAt;

    // ===============================
    // ENUMS
    // ===============================

    public enum AlertCategory {
        SYSTEM_HEALTH,
        SECURITY,
        PERFORMANCE,
        BUSINESS_KPI,
        USER_ACTIVITY,
        FRAUD_DETECTION
    }

    public enum SeverityLevel {
        CRITICAL,
        HIGH,
        MEDIUM,
        LOW,
        INFO
    }

    public enum PriorityLevel {
        URGENT,
        HIGH,
        NORMAL,
        LOW
    }

    public enum AlertStatus {
        ACTIVE,
        ACKNOWLEDGED,
        RESOLVED,
        DISMISSED,
        ESCALATED
    }

    public enum ThresholdType {
        ABOVE,
        BELOW,
        EQUAL,
        CHANGE_RATE
    }

    public enum ImpactLevel {
        CRITICAL,
        HIGH,
        MEDIUM,
        LOW
    }

    // ===============================
    // LIFECYCLE CALLBACKS
    // ===============================
    
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    // ===============================
    // HELPER METHODS
    // ===============================

    /**
     * Kiểm tra xem alert có đang active không
     */
    public boolean isActive() {
        return AlertStatus.ACTIVE.equals(this.alertStatus);
    }

    /**
     * Kiểm tra xem alert có cần xử lý khẩn cấp không
     */
    public boolean isCritical() {
        return SeverityLevel.CRITICAL.equals(this.severityLevel) || 
               PriorityLevel.URGENT.equals(this.priorityLevel);
    }

    /**
     * Kiểm tra xem alert có hết hạn không
     */
    public boolean isExpired() {
        return this.expiresAt != null && LocalDateTime.now().isAfter(this.expiresAt);
    }

    /**
     * Tính thời gian từ khi tạo đến hiện tại (phút)
     */
    public long getAgeInMinutes() {
        return Duration.between(this.createdAt, LocalDateTime.now()).toMinutes();
    }

    /**
     * Acknowledge alert
     */
    public void acknowledge(User user, String note) {
        this.alertStatus = AlertStatus.ACKNOWLEDGED;
        this.acknowledgedBy = user;
        this.acknowledgedAt = LocalDateTime.now();
        this.acknowledgedNote = note;
    }

    /**
     * Resolve alert
     */
    public void resolve(User user, String note) {
        this.alertStatus = AlertStatus.RESOLVED;
        this.resolvedBy = user;
        this.resolvedAt = LocalDateTime.now();
        this.resolutionNote = note;
        this.resolutionTimeMinutes = (int) getAgeInMinutes();
        this.isResolved = true;
    }

    /**
     * Format alert for display
     */
    public String getDisplayTitle() {
        return String.format("[%s] %s - %s", 
            this.severityLevel.name(), 
            this.alertCategory.name(), 
            this.alertTitle
        );
    }

    /**
     * Get color for UI display based on severity
     */
    public String getDisplayColor() {
        switch (this.severityLevel) {
            case CRITICAL:
                return "#DC2626"; // Red
            case HIGH:
                return "#EA580C"; // Orange
            case MEDIUM:
                return "#D97706"; // Amber
            case LOW:
                return "#059669"; // Green
            case INFO:
                return "#0284C7"; // Blue
            default:
                return "#6B7280"; // Gray
        }
    }

    /**
     * Kiểm tra có cần escalate không
     */
    public boolean shouldEscalate() {
        if (this.alertStatus == AlertStatus.ACTIVE && 
            this.severityLevel == SeverityLevel.CRITICAL &&
            getAgeInMinutes() > 30) { // 30 phút chưa xử lý
            return true;
        }
        return false;
    }

    /**
     * Tạo alert code tự động
     */
    public static String generateAlertCode(AlertCategory category, String type) {
        String prefix = category.name().substring(0, 3).toUpperCase();
        long timestamp = System.currentTimeMillis();
        return String.format("%s_%s_%d", prefix, type.toUpperCase(), timestamp % 100000);
    }
}
