spring.application.name=BACKEND
spring.datasource.url=jdbc:mysql://localhost:3306/secondhand_sale?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=29092004H@u
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=30
# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.org.hibernate.engine.transaction.jta.platform.i.JtaPlatformInitiator=WARN
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# ===============================
# OAuth2 Login Configuration
# ===============================

## Google Login
spring.security.oauth2.client.registration.google.client-id=196653940350-72al3e1o7022u3endbsnfa4s89k66gob.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

## Facebook Login
spring.security.oauth2.client.registration.facebook.client-id=1201867234769030
spring.security.oauth2.client.registration.facebook.client-secret=fe6902901b3cd79d54e7fbc0bf41cdc6
spring.security.oauth2.client.registration.facebook.scope=public_profile,email
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


# ===============================
# Payment Configuration
# ===============================

# ===============================
# Server Configuration
# ===============================
server.port=8080
server.servlet.context-path=/oldtech
