package com.example.BACKEND_OLDTECH_WEBSITE.DTO.Admin;

import com.example.BACKEND_OLDTECH_WEBSITE.ETL.Model.AdminAlert.*;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * Admin Alert Dashboard DTO - Dữ liệu cho dashboard cảnh báo admin
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AdminAlertDashboardDTO {

    // ===============================
    // ALERT SUMMARY
    // ===============================
    
    private Long totalActiveAlerts;
    private Long totalCriticalAlerts;
    private Long totalResolvedToday;
    private Double averageResolutionTimeMinutes;
    
    // ===============================
    // CATEGORY BREAKDOWN
    // ===============================
    
    private Map<String, Long> alertsByCategory;
    private Map<String, Long> alertsBySeverity;
    private Map<String, Long> alertsByStatus;
    
    // ===============================
    // TREND DATA
    // ===============================
    
    private Map<String, Long> alertTrendLast24Hours;
    private Map<String, Long> alertTrendLast7Days;
    
    // ===============================
    // TOP METRICS
    // ===============================
    
    private Map<String, Long> topAlertMetrics;
    private Map<String, Long> topAffectedComponents;
    
    // ===============================
    // PERFORMANCE METRICS
    // ===============================
    
    private Double averageResponseTimeMinutes;
    private Double mttrMinutes; // Mean Time To Resolve
    private Long slaViolationsCount;
    
    // ===============================
    // BUSINESS IMPACT
    // ===============================
    
    private Long highBusinessImpactAlerts;
    private Long securityAlertsCount;
    private Long fraudAlertsCount;
    
    // ===============================
    // METADATA
    // ===============================
    
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime lastUpdated;
    
    private String reportPeriod;
    private String dataQuality;
    
    // ===============================
    // HELPER METHODS
    // ===============================
    
    /**
     * Tính tỷ lệ alert critical
     */
    public Double getCriticalAlertPercentage() {
        if (totalActiveAlerts == null || totalActiveAlerts == 0) {
            return 0.0;
        }
        return (totalCriticalAlerts != null ? totalCriticalAlerts.doubleValue() / totalActiveAlerts.doubleValue() * 100 : 0.0);
    }
    
    /**
     * Kiểm tra có alert cần chú ý không
     */
    public Boolean hasUrgentAlerts() {
        return totalCriticalAlerts != null && totalCriticalAlerts > 0;
    }
    
    /**
     * Lấy status của alert system
     */
    public String getSystemStatus() {
        if (totalCriticalAlerts != null && totalCriticalAlerts > 5) {
            return "CRITICAL";
        } else if (totalActiveAlerts != null && totalActiveAlerts > 20) {
            return "WARNING";
        } else {
            return "HEALTHY";
        }
    }
}

/**
 * Admin Alert Summary DTO - Tóm tắt alert cho widget
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
class AdminAlertSummaryDTO {
    
    private String alertCode;
    private AlertCategory category;
    private SeverityLevel severity;
    private String title;
    private String description;
    private String affectedComponent;
    private BigDecimal currentValue;
    private BigDecimal thresholdValue;
    private String suggestedAction;
    private Boolean manualActionRequired;
    private Long ageInMinutes;
    
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createdAt;
    
    private String displayColor;
    private String priorityLabel;
}

/**
 * Admin Alert Detail DTO - Chi tiết alert đầy đủ
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
class AdminAlertDetailDTO {
    
    private Long alertId;
    private String alertCode;
    private AlertCategory alertCategory;
    private String alertType;
    private String alertTitle;
    private String alertDescription;
    
    private SeverityLevel severityLevel;
    private PriorityLevel priorityLevel;
    private AlertStatus alertStatus;
    private Boolean isAutoGenerated;
    
    private String metricName;
    private BigDecimal currentValue;
    private BigDecimal thresholdValue;
    private ThresholdType thresholdType;
    
    private String affectedComponent;
    private ImpactLevel impactLevel;
    private String businessImpact;
    private String technicalDetails;
    
    private String relatedEntityType;
    private Long relatedEntityId;
    private String correlationId;
    
    private String suggestedAction;
    private String autoActionTaken;
    private Boolean manualActionRequired;
    
    // Acknowledgment info
    private String acknowledgedByUsername;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime acknowledgedAt;
    private String acknowledgedNote;
    
    // Resolution info
    private String resolvedByUsername;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime resolvedAt;
    private String resolutionNote;
    private Integer resolutionTimeMinutes;
    
    // Performance metrics
    private Integer responseTimeMinutes;
    private Boolean slaBreach;
    
    // Recurrence info
    private Boolean isRecurring;
    private String recurrencePattern;
    private Integer occurrenceCount;
    
    // Timestamps
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createdAt;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime updatedAt;
    
    // Display helpers
    private String displayTitle;
    private String displayColor;
    private Long ageInMinutes;
    private Boolean isCritical;
    private Boolean shouldEscalate;
}

/**
 * Admin Alert Filter DTO - Bộ lọc cho search
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
class AdminAlertFilterDTO {
    
    private AlertCategory category;
    private SeverityLevel severity;
    private AlertStatus status;
    private String metricName;
    private String affectedComponent;
    
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime startDate;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime endDate;
    
    private Boolean unacknowledgedOnly;
    private Boolean criticalOnly;
    private Boolean manualActionRequired;
    
    private String keyword;
    private String sortBy;
    private String sortDirection;
    
    private Integer page;
    private Integer size;
}

/**
 * Admin Alert Trend DTO - Dữ liệu xu hướng alert
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
class AdminAlertTrendDTO {
    
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime timestamp;
    
    private Long totalAlerts;
    private Long criticalAlerts;
    private Long highAlerts;
    private Long mediumAlerts;
    private Long lowAlerts;
    
    private Long systemHealthAlerts;
    private Long securityAlerts;
    private Long performanceAlerts;
    private Long businessKpiAlerts;
    private Long fraudAlerts;
    
    private Long resolvedAlerts;
    private Double averageResolutionTime;
    
    private String period; // HOUR, DAY, WEEK, MONTH
}

/**
 * Admin Alert Metrics DTO - Metrics tổng hợp
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
class AdminAlertMetricsDTO {
    
    // Volume metrics
    private Long totalAlertsGenerated;
    private Long alertsResolvedOnTime;
    private Long alertsEscalated;
    private Double alertVolumeGrowthPercent;
    
    // Performance metrics
    private Double averageResolutionTimeMinutes;
    private Double medianResolutionTimeMinutes;
    private Double mttrMinutes;
    private Double slaCompliancePercent;
    
    // Quality metrics
    private Double falsePositiveRate;
    private Double alertAccuracyPercent;
    private Long duplicateAlertsConsolidated;
    
    // Business impact
    private Long highBusinessImpactAlerts;
    private Long criticalSystemOutages;
    private Long securityIncidentsDetected;
    
    // Operational metrics
    private Long alertsRequiringManualAction;
    private Long automatedResolutions;
    private Double automationRate;
    
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime reportGeneratedAt;
    
    private String reportPeriod;
    private String dataSource;
}
